kind: pipeline
name: x86_64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: alpine:edge
    commands:
      - nproc && grep Mem /proc/meminfo && df -hT .
      - echo http://dl-cdn.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories
      - apk add gcc-arm-none-eabi dtc dtc-dev make python2
      - make -j$(nproc) TOOLCHAIN_PREFIX=arm-none-eabi- msm8916-secondary

trigger:
  event: [push, pull_request, tag]
